services:
  - type: web
    name: walkify-server
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    envVars:
      - key: PORT
        value: "3001"
    healthCheckPath: /api/health
